### ISSUE TITLE
VNC remote access vulnerabilities

### ISSUE THREAD

**Issue by Neustradamus** [veyon/ultravnc#2]
There are VNC remote access vulnerabilities: https://www.kaspersky.com/blog/vnc-vulnerabilities/31462/

**Comment by tobydox** [comment]
Please note that this is only an unofficial mirror of the UltraVNC SVN repository. All information regarding UltraVNC and Veyon can be found at https://veyon.io/blog/2019/12/02/vnc-vulnerabilities/

**Comment by Neustradamus** [comment]
Thanks @tobydox for the article on the website! :)
