### ISSUE TITLE
VNCViewer - Chat error

### ISSUE THREAD

**Issue by SplinterCode2020** [veyon/ultravnc#3]
With vncViewer release 1.2.4.0 the Chat function cause an abort.

![immagine](https://user-images.githubusercontent.com/61002457/74412657-34438300-4e3e-11ea-81e1-35951a2ad337.png)

Debugging on  Vstudio 2017 the execution of the program stops at various points.

Sometime on strnlen.cpp
![immagine](https://user-images.githubusercontent.com/61002457/74413324-7b7e4380-4e3f-11ea-9924-17da9020be4b.png)

or on TextChat::DoDialog()
![immagine](https://user-images.githubusercontent.com/61002457/74413574-f3e50480-4e3f-11ea-88d5-43eb3dda5334.png)

I hope that  someone can resolve this problem.

Thank you.

**Comment by tobydox** [comment]
This is a read-only Git clone of the UltraVNC SVN repository. We're not involved in the UltraVNC development. Please contact the UltraVNC authors instead.
